build: false

environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\continuous-integration\\appveyor\\run_with_env.cmd"
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python36-x64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%CMD_IN_ENV% pip install -U -r requirements.txt"

test_script:
  - "%PYTHON%\\python.exe run.py"

on_success:
  - "%PYTHON%\\python.exe run.py"
