environment:
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python35-x64"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install wheel"

test_script:
  - "%CMD_IN_ENV% pip install -U -r requirements.txt"
  - "%PYTHON%\\python.exe run.py"

on_success:
  - "%PYTHON%\\python.exe run.py"

artifacts: off
