environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON_VERSION: "3.6.x"
    - PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
    - PYTHON_VERSION: "3.6.x"
    - PYTHON_ARCH: "64"
install:
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""
  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "pip install --disable-pip-version-check --user --upgrade pip"
  - "%CMD_IN_ENV% pip install -r dev-requirements.txt"

test_script:
  - "%CMD_IN_ENV% python run.py"
