version: '2'

services:
  db:
    image: mongo:3.2.9
    ports:
      - "27017:27017"

  bot:
    build: .
    environment:
      DATABASE_URL: 'mongodb://db:27017'
    volumes:
      - .:/sigma
      - ./fonts:/usr/share/fonts
    ports:
      - "37812:37812"
    depends_on:
      - db
